// Mocks generated by Mockito 5.4.2 from annotations
// in construction_diary/test/features/home/home_store_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:construction_diary/app/features/home/data/datasources/home_datasource.dart'
    as _i2;
import 'package:construction_diary/app/features/home/domain/entities/diary_entry.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HomeDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeDataSourceImpl extends _i1.Mock
    implements _i2.HomeDataSourceImpl {
  @override
  _i3.Future<bool> createDiaryEntry(_i4.DiaryEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDiaryEntry,
          [entry],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
